### PR TITLE
build: use official package name

### LINKED ISSUE #15: Dockerfile is broken
`docker build .`  fails, for various reasons. I think that the separation to libraries broke it.

### PR DESCRIPTION
**Pull request by simon3z**
Fixes #15

### CODE REVIEW

**Comment by simon3z** [comment]
@pweil- this is a replacement for #16. I prefer to use the official package name. I hope I got it all right and you don't mind if I fix this ASAP (we're a little in a rush). Thanks.

**Comment by enoodle** [comment]
LGTM

**Comment by enoodle** [comment]
:+1:

**Comment by pweil-** [comment]
awesome, I was hoping this is what we were going to do.  I'll fix my local env. :+1:

**Pull request merged**
